### ISSUE TITLE
Download all history of data for pairs for all exchanges

### ISSUE THREAD

**Issue by Metaphor31** [stefs304/cryCompare#5]
Hi, 

I would like to know how to get historical data for all crypto from one exchange only. And then re do it for each exchange. 

Thanks

**Comment by stefs304** [comment]
Hi, unfortunately there is no exchange-snapshot request for cryptocompare api, but you can get around this by calling a pricemulti request with fsyms set to the list of coins you need (you can get full list by calling coinlist request). And ofc you specify which exchange you want with e param.

**Comment by stefs304** [comment]
I'll close this issue now since it is related to Cryptocompare API capabilities. I hope I gave you good solution though, let me know if there is anything else I can help with.
