### ISSUE TITLE
Full Support of API Requests

### ISSUE THREAD

**Issue by slavakurilyak** [stefs304/cryCompare#8]
I would love to see full support for Cryptocompare API requests, which currently has 12 categories of data:

1. CoinList
2. Price
3. PriceHistorical
4. CoinSnapshot
5. CoinSnapshotFullByID
6. Social Stats
7. HistoMinute
8. HistoHour
9. HistoDay
10. MiningContracts
11. MiningEquipment
12. TopPairs

**Comment by stefs304** [comment]
Hi Slava, that is a good idea. Most of the API requests you mentioned are already implemented, with exception of 6,10,11 and 12. I should see to those in the following week or two. Thanks for suggestion

**Comment by stefs304** [comment]
Couldn't sleep last night so I implemented all API requests :)
- TopPairs is now function in *price* module
- SocialsStats is part of new *social* module
- MiningEquipment request is also in *social* module
